### ISSUE TITLE
v2.1 M1 macbook Air 실행시 오류발생 (해결)

### ISSUE THREAD

**Issue by ufshg** [op06072/NeoAsitop#1]
오류 코드
`Swift/ContiguousArrayBuffer.swift: 588: Fatal error: Index out of range - trace trap`

제작자님과 디버깅한 결과 fanless모델인 Air에서 fan에 대한 정보를 읽어오지 못해 발생하는 오류로 확인되었습니다.
다음 버전에서 수정해주실겁니다!

**Comment by op06072** [comment]
> 오류 코드 `Swift/ContiguousArrayBuffer.swift: 588: Fatal error: Index out of range - trace trap`
> 
> 제작자님과 디버깅한 결과 fanless모델인 Air에서 fan에 대한 정보를 읽어오지 못해 발생하는 오류로 확인되었습니다. 다음 버전에서 수정해주실겁니다!

v2.2가 릴리즈 되었으며 해결되었습니다. 현재 이슈를 close하겠습니다.
